# Generated by Django 5.1.3 on 2024-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.CharField(choices=[('PUB', 'published'), ('PRI', 'private')], default='PUB'),
        ),
    ]
